version: '3'
services:
  db:
    image: postgres
  app:
    build: .
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true

volumes:
  bundle:
